(() => {
  const LOCAL_KEY = "reppilot-user-profile";
  const WEIGHT_HISTORY_KEY = "reppilot-weight-history";
  const readLocal=()=>{try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||"{}")||{}}catch{return{}}};
  const writeLocal=p=>localStorage.setItem(LOCAL_KEY,JSON.stringify(p));
  const readWeightHistory=()=>{try{return JSON.parse(localStorage.getItem(WEIGHT_HISTORY_KEY)||"[]")||[]}catch{return[]}};
  const writeWeightHistory=r=>localStorage.setItem(WEIGHT_HISTORY_KEY,JSON.stringify(r));
  async function getUser(){const c=window.repPilotSupabase;if(!c)return null;const{data}=await c.auth.getUser();return data?.user||null}
  async function loadCloudProfile(){const c=window.repPilotSupabase,u=await getUser();if(!c||!u)return readLocal();const{data,error}=await c.from("user_profiles").select("height_cm,weight_kg,updated_at").eq("user_id",u.id).maybeSingle();if(error)return readLocal();if(data){const p={heightCm:Number(data.height_cm)||null,weightKg:Number(data.weight_kg)||null,updatedAt:data.updated_at||null};writeLocal(p);return p}return readLocal()}
  async function saveCloudProfile(p){const c=window.repPilotSupabase,u=await getUser();if(!c||!u)return false;const{error}=await c.from("user_profiles").upsert({user_id:u.id,height_cm:p.heightCm,weight_kg:p.weightKg,updated_at:new Date().toISOString()});return !error}
  function renderProfile(p=readLocal()){const s=document.getElementById("profileSummary"),h=document.getElementById("profileWeightHistory");if(!s||!h)return;if(p.heightCm&&p.weightKg){s.innerHTML=`<div class="profile-values"><div><strong>${Number(p.weightKg).toLocaleString("de-DE",{maximumFractionDigits:1})} kg</strong><small>Gewicht</small></div><div><strong>${Number(p.heightCm).toLocaleString("de-DE")} cm</strong><small>Größe</small></div><div><strong>${(Number(p.weightKg)*.5).toLocaleString("de-DE",{maximumFractionDigits:1})} kg</strong><small>Hanging Leg Raises</small></div></div>`}else{s.innerHTML=`<p class="muted">Trage Größe und Körpergewicht ein. Körpergewichtsübungen werden dann automatisch berechnet.</p>`}const rows=readWeightHistory().slice(-6).reverse();h.innerHTML=rows.length>1?`<div class="weight-history"><small>GEWICHTSVERLAUF</small>${rows.map(r=>`<span><b>${Number(r.weightKg).toLocaleString("de-DE",{maximumFractionDigits:1})} kg</b><small>${new Date(r.at).toLocaleDateString("de-DE")}</small></span>`).join("")}</div>`:""}
  function ensureProfileUI(){if(document.getElementById("profile"))return;const main=document.querySelector("main"),nav=document.querySelector("nav");if(!main||!nav)return;const section=document.createElement("section");section.id="profile";section.className="view";section.innerHTML=`<h2>Profil</h2><article class="card profile-card"><div class="profile-head"><div><small>DEIN PROFIL</small><h2>Körperdaten</h2></div><button id="editProfileBtn" class="secondary">Bearbeiten</button></div><div id="profileSummary"></div><div id="profileForm" hidden><label for="profileHeight">Größe</label><div class="weight"><input id="profileHeight" type="number" min="100" max="250" step="1" inputmode="numeric"><span>cm</span></div><label for="profileWeight">Körpergewicht</label><div class="weight"><input id="profileWeight" type="number" min="30" max="300" step="0.1" inputmode="decimal"><span>kg</span></div><button id="saveProfileBtn" class="wide">Profil speichern</button></div><div id="profileWeightHistory"></div></article>`;main.appendChild(section);const btn=document.createElement("button");btn.dataset.view="profile";btn.textContent="Profil";nav.appendChild(btn);nav.style.gridTemplateColumns="repeat(4,1fr)";btn.onclick=()=>{document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));section.classList.add("active");btn.classList.add("active");loadCloudProfile().then(renderProfile)};document.getElementById("editProfileBtn").onclick=async()=>{const p=await loadCloudProfile();document.getElementById("profileHeight").value=p.heightCm||"";document.getElementById("profileWeight").value=p.weightKg||"";document.getElementById("profileForm").hidden=false};document.getElementById("saveProfileBtn").onclick=async()=>{const heightCm=Number(document.getElementById("profileHeight").value),weightKg=Number(document.getElementById("profileWeight").value);if(!heightCm||!weightKg)return;const now=new Date().toISOString(),p={heightCm,weightKg,updatedAt:now};writeLocal(p);const rows=readWeightHistory();if(!rows.length||Number(rows[rows.length-1].weightKg)!==weightKg){rows.push({weightKg,at:now});writeWeightHistory(rows)}await saveCloudProfile(p);document.getElementById("profileForm").hidden=true;renderProfile(p)};loadCloudProfile().then(renderProfile)}
  window.repPilotProfile={get:readLocal,refresh:loadCloudProfile,bodyweightLoad:(factor=.5)=>Number(readLocal().weightKg||0)*factor};
  document.addEventListener("DOMContentLoaded",ensureProfileUI);if(document.readyState!=="loading")ensureProfileUI();
})();